### PR TITLE
added twitter authentication, to access go through /front, set twitte…

### PR DESCRIPTION
**Pull request by abdullateef97**
#1 
#Twitter Auth
added twitter authentication
made the / page inaccessible unless authenticated
try going through /front
replace the consumer key, secret in the config file
stored details of users that have logged in to the app

### CODE REVIEW

**Comment by Asutosh989** [comment]
Hi, great work. Thanks for the effort. Before merging, I want to know if it is working or not?

**Comment by abdullateef97** [comment]
it is, you have to generate ur twitter api key and secret if you dont have one before and place it in the config file

**Comment by Asutosh989** [comment]
Can you mention what should be the callback url and is the below mentioned code correct as it is not redirecting me back to the app

`

// handle callback after twitter has authenticated the user

router.get('/auth/twitter/callback',
        
 passport.authenticate('twitter', {

            // successRedirect : '/',

            failureRedirect : '/front'

        }),

      (req,res,next)=>{
        res.redirect('/');
      });
`

Error is coming as below 

> Error: This feature is temporarily unavailable
Strategy.parseErrorResponse

**Comment by Asutosh989** [comment]
Do tell how to resolve this error?


> This feature is temporarily unavailable

undefined

Error: This feature is temporarily unavailable
    at Strategy.parseErrorResponse (/home/zectrosan/Documents/node/tweet-split/node_modules/passport-twitter/lib/strategy.js:206:12)
    at Strategy.OAuthStrategy._createOAuthError (/home/zectrosan/Documents/node/tweet-split/node_modules/passport-oauth1/lib/strategy.js:393:16)
    at /home/zectrosan/Documents/node/tweet-split/node_modules/passport-oauth1/lib/strategy.js:154:43
    at /home/zectrosan/Documents/node/tweet-split/node_modules/oauth/lib/oauth.js:465:22
    at passBackControl (/home/zectrosan/Documents/node/tweet-split/node_modules/oauth/lib/oauth.js:397:13)
    at IncomingMessage.<anonymous> (/home/zectrosan/Documents/node/tweet-split/node_modules/oauth/lib/oauth.js:409:9)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

**Pull request merged**
