### PR TITLE
Fix the twitter authentication and redirect

### PR DESCRIPTION
**Pull request by email2vimalraj**
- Removed unnecessary User model and mongoose library
- Fixed the passport middleware with proper callbacks
- Added the user display name in the navbar
- Removed unnecessary configs
- Updated the readme with required information to setup

### CODE REVIEW

**Comment by email2vimalraj** [comment]
@Asutosh989 : Hope this PR resolves issue #1, since there were couple of issues introduced by previous PR for the same issue and also cleaned up some code.

**Comment by Asutosh989** [comment]
@email2vimalraj I will check the PR and then merge it. Thanks for the effort.

**Comment by Asutosh989** [comment]
The changes looks fine. Its working well and good. But there are some twit config errors, it cant access the consumer key from .env

error showing up

Twit config must include `consumer_key` when using user auth.

Although I have included all required info in the .env file.

**Comment by email2vimalraj** [comment]
I know this error, it is not the code issue. In couple of minutes, I'll
update this PR with readme instructions.

**Comment by Asutosh989** [comment]
Yes, I could fix this error, But I am not able to get the Twit config error which is not able to access the ' consumer -key'.

**Comment by email2vimalraj** [comment]
@Asutosh989 : Updated the readme with more information on generating the access token, the exception you faced is due to there was no access token generated for the twitter app. The readme instruction will help now.

And regarding Twit config error, please give me more information on how to reproduce.

**Comment by Asutosh989** [comment]
Hi @email2vimalraj the error of Twit config looks something like this although I have included all the required consumer key and other stuffs in the .env file.

> Twit config must include `consumer_key` when using user auth.

> undefined
> 
> Error: Twit config must include `consumer_key` when using user auth.
>     at /home/zectrosan/Documents/hacktoberfest/temp/twitter-splitter/node_modules/twit/lib/twitter.js:491:13
>     at Array.forEach (native)
>     at Twitter._validateConfigOrThrow (/home/zectrosan/Documents/hacktoberfest/temp/twitter-splitter/node_modules/twit/lib/twitter.js:488:17)
>     at new Twitter (/home/zectrosan/Documents/hacktoberfest/temp/twitter-splitter/node_modules/twit/lib/twitter.js:58:8)
>     at Object.router.get [as handle] (/home/zectrosan/Documents/hacktoberfest/temp/twitter-splitter/src/routes/tweet.js:8:13)
>     at next_layer (/home/zectrosan/Documents/hacktoberfest/temp/twitter-splitter/node_modules/express/lib/router/route.js:103:13)
>     at Route.dispatch (/home/zectrosan/Documents/hacktoberfest/temp/twitter-splitter/node_modules/express/lib/router/route.js:107:5)
>     at /home/zectrosan/Documents/hacktoberfest/temp/twitter-splitter/node_modules/express/lib/router/index.js:195:24
>     at Function.proto.process_params (/home/zectrosan/Documents/hacktoberfest/temp/twitter-splitter/node_modules/express/lib/router/index.js:251:12)
>     at next (/home/zectrosan/Documents/hacktoberfest/temp/twitter-splitter/node_modules/express/lib/router/index.js:189:19)
>     at Function.proto.handle (/home/zectrosan/Documents/hacktoberfest/temp/twitter-splitter/node_modules/express/lib/router/index.js:234:5)
>     at Layer.router [as handle] (/home/zectrosan/Documents/hacktoberfest/temp/twitter-splitter/node_modules/express/lib/router/index.js:23:12)
>     at trim_prefix (/home/zectrosan/Documents/hacktoberfest/temp/twitter-splitter/node_modules/express/lib/router/index.js:226:17)
>     at /home/zectrosan/Documents/hacktoberfest/temp/twitter-splitter/node_modules/express/lib/router/index.js:198:9
>     at Function.proto.process_params (/home/zectrosan/Documents/hacktoberfest/temp/twitter-splitter/node_modules/express/lib/router/index.js:251:12)
>     at next (/home/zectrosan/Documents/hacktoberfest/temp/twitter-splitter/node_modules/express/lib/router/index.js:189:19)

**Comment by email2vimalraj** [comment]
Let me have a look.

On 22-Oct-2017 9:53 PM, "Asutosh" <notifications@github.com> wrote:

Hi @email2vimalraj <https://github.com/email2vimalraj> the error of Twit
config looks something like this.

Twit config must include consumer_key when using user auth.

undefined

Error: Twit config must include consumer_key when using user auth.
at /home/zectrosan/Documents/hacktoberfest/temp/twitter-
splitter/node_modules/twit/lib/twitter.js:491:13
at Array.forEach (native)
at Twitter._validateConfigOrThrow (/home/zectrosan/Documents/
hacktoberfest/temp/twitter-splitter/node_modules/twit/lib/twitter.js:488:17)
at new Twitter (/home/zectrosan/Documents/hacktoberfest/temp/twitter-
splitter/node_modules/twit/lib/twitter.js:58:8)
at Object.router.get [as handle] (/home/zectrosan/Documents/
hacktoberfest/temp/twitter-splitter/src/routes/tweet.js:8:13)

at next_layer (/home/zectrosan/Documents/hacktoberfest/temp/twitter-
splitter/node_modules/express/lib/router/route.js:103:13)
at Route.dispatch (/home/zectrosan/Documents/hacktoberfest/temp/twitter-
splitter/node_modules/express/lib/router/route.js:107:5)
at /home/zectrosan/Documents/hacktoberfest/temp/twitter-
splitter/node_modules/express/lib/router/index.js:195:24
at Function.proto.process_params (/home/zectrosan/Documents/
hacktoberfest/temp/twitter-splitter/node_modules/express/
lib/router/index.js:251:12)
at next (/home/zectrosan/Documents/hacktoberfest/temp/twitter-
splitter/node_modules/express/lib/router/index.js:189:19)
at Function.proto.handle (/home/zectrosan/Documents/
hacktoberfest/temp/twitter-splitter/node_modules/express/
lib/router/index.js:234:5)
at Layer.router [as handle] (/home/zectrosan/Documents/
hacktoberfest/temp/twitter-splitter/node_modules/express/
lib/router/index.js:23:12)
at trim_prefix (/home/zectrosan/Documents/hacktoberfest/temp/twitter-
splitter/node_modules/express/lib/router/index.js:226:17)
at /home/zectrosan/Documents/hacktoberfest/temp/twitter-
splitter/node_modules/express/lib/router/index.js:198:9

at Function.proto.process_params (/home/zectrosan/Documents/
hacktoberfest/temp/twitter-splitter/node_modules/express/
lib/router/index.js:251:12)
at next (/home/zectrosan/Documents/hacktoberfest/temp/twitter-
splitter/node_modules/express/lib/router/index.js:189:19)

—

You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Asutosh989/twitter-splitter/pull/15#issuecomment-338489927>,
or mute the thread

**Comment by Asutosh989** [comment]
Hi @email2vimalraj have you found out the source of the above error?

**Comment by email2vimalraj** [comment]
Hi Asutosh,

Thanks for reminding, I've got busy with other things lately.

I'll have a look tomorrow and update here. Sorry for an inconvenience
caused.

**Comment by Asutosh989** [comment]
Hi @email2vimalraj any progress?

**Comment by email2vimalraj** [comment]
Not yet Asutosh, two more days pls.

**Comment by Asutosh989** [comment]
sure.

**Comment by Asutosh989** [comment]
Hi @email2vimalraj any progress related to the issue?

**Comment by Asutosh989** [comment]
Hi @email2vimalraj can you resolve this now?

**Pull request closed without merging**
